use std::io;

fn main() {

    println!("Fibonacci generator");
    println!("Type \"q\" to end the program");

    loop {
        // Create string.
        let mut number = String::new();

        println!("\nEnter a positive integer:");

        // Get user input.
        io::stdin()
        .read_line(&mut number)
        .expect("Failed to read line");

        // Check if they want to quit.
        if number.trim() == "q" {
            break;
        }

        // Parse number.
        let number: u64 = match number.trim().parse() {
            Ok(num) => num,
            Err(_) => continue,
        };

        // Print results.
        println!("{} is the Fibonacci number of {}", fibonacci(number), number);
    }
}

// The Fibonacci sequence is a pattern of numbers generated by summing the previous two numbers in the sequence.
// n is the parameter to our function. 
// n is the number we want to generate the fibonacci number of.

fn fibonacci(n: u64) -> u64 {
    if n == 1 || n == 2 {
        1
    } else {
        fibonacci(n - 1) + fibonacci(n - 2)
    }
}